#!/bin/sh

# OpenHA postinstall script

BASEDIR=${BASEDIR:-/}

if [ "X${BASEDIR}" = "X" ] ; then
  echo "Error => BASEDIR environment variable have to be defined. Aborting."
  exit 1
fi

# removing leading / if present
TRAILING=`echo "$BASEDIR" | sed 's/^.*\(.\)$/\1/'`
if [ "${TRAILING}" = "/" ] ; then
  MYBASEDIR=`echo "$BASEDIR" | sed 's/.$//'`
else
  MYBASEDIR=$BASEDIR
fi

LD_LIBRARY_PATH=${MYBASEDIR}/usr/local/lib; export LD_LIBRARY_PATH
EZ=${MYBASEDIR}/usr/local/cluster

export EZ
. $EZ/env.sh
[ ! -d $EZ -o ! -d $EZ/bin ] && exit 1
[ ! -d $EZ/conf ] && mkdir -p $EZ/conf
[ ! -d $EZ/log/proc ] && mkdir -p $EZ/log/proc
[ ! -d $EZ/services ] && mkdir -p $EZ/services

ln -sf $EZ/ezha ${MYBASEDIR}/etc/rc3.d/S99cluster
ln -sf $EZ/ezha ${MYBASEDIR}/etc/rc0.d/K01cluster
ln -sf $EZ/ezha ${MYBASEDIR}/etc/rcS.d/K01cluster

exit 0
