#!/bin/sh

# OpenHA preremove script

BASEDIR=${BASEDIR:-/}

# removing leading / if present
TRAILING=`echo "$BASEDIR" | sed 's/^.*\(.\)$/\1/'`
if [ "${TRAILING}" = "/" ] ; then
  MYBASEDIR=`echo "$BASEDIR" | sed 's/.$//'`
else
  MYBASEDIR=$BASEDIR
fi

[ ! -d $LOG_D ] && mkdir $LOD_D

log () {
    exec >> $LOG_D/postinstall.log 2>&1
    DATE=`date +"%Y-%m-%d %H:%M:%S"`
    printf "%b\n" "$DATE $*"
}

type systemctl >> /dev/null 2>&1 && {
    systemctl disable -q opensvc-openha.service
    rm -f /etc/systemd/system/opensvc-openha.service
    systemctl -q daemon-reload
}

type update-rc.d >> /dev/null 2>&1 && {
   if test -f /etc/init.d/ezha -o -h /etc/init.d/ezha
   then
       log "updatercd_launch : removing existing /etc/init.d/ezha"
       update-rc.d -f ezha remove >> /dev/null 2>&1
       rm -f /etc/init.d/ezha
   fi

   if test -f /etc/init.d/openha -o -h /etc/init.d/openha
   then
       log "updatercd_launch : removing existing /etc/init.d/openha"
       update-rc.d -f openha remove >> /dev/null 2>&1
       rm -f /etc/init.d/openha
   fi
}

type chkconfig >> /dev/null 2>&1 && {
   if test -f /etc/init.d/ezha -o -h /etc/init.d/ezha
   then
       log "chkconfig_launch : removing existing /etc/init.d/ezha"
       chkconfig --del ezha >> /dev/null 2>&1
       rm -f /etc/init.d/ezha
   fi

   if test -f /etc/init.d/openha -o -h /etc/init.d/openha
   then
       log "chkconfig_launch : removing existing /etc/init.d/openha"
       chkconfig --del openha >> /dev/null 2>&1
       rm -f /etc/init.d/openha
   fi
}

rm -f ${MYBASEDIR}/etc/rc?.d/S99openha
rm -f ${MYBASEDIR}/etc/rc?.d/K01openha
rm -f ${MYBASEDIR}/etc/rc?.d/S99cluster
rm -f ${MYBASEDIR}/etc/rc?.d/K01cluster

exit 0
